-- Populate remaining test tables
USE StackOverflowMini;
GO

-- Populate 50-column table
INSERT INTO dbo.Test_50_Columns (
    C01, C02, C03, C04, C05, C06, C07, C08, C09, C10,
    C11, C12, C13, C14, C15, C16, C17, C18, C19, C20,
    V01, V02, V03, V04, V05, V06, V07, V08, V09, V10,
    V11, V12, V13, V14, V15,
    F01, F02, F03, F04, F05, F06, F07, F08, F09, F10,
    Date1, Date2, Date3
)
SELECT TOP 1000
    'C01-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C02-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C03-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C04-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C05-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C06-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C07-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C08-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C09-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C10-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C11-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C12-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C13-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C14-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C15-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C16-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C17-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C18-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C19-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C20-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 2,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 3,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 4,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 5,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 6,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 7,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 8,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 9,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 10,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 11,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 12,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 13,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 14,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 15,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 2 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 3 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 4 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 5 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 6 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 7 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 8 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 9 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 10 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 11 = 0 THEN 1 ELSE 0 END,
    DATEADD(DAY, -(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 365), GETDATE()),
    DATEADD(HOUR, -(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 24), GETDATE()),
    DATEADD(MINUTE, -(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 60), GETDATE())
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate 25-column complex table
INSERT INTO dbo.Test_25_Complex (
    Amount1, Amount2, Amount3, Amount4, Amount5,
    Price1, Price2, Price3, Price4, Price5,
    Text1, Text2, Text3, Text4, Text5,
    Code1, Code2, Code3, Code4, Code5,
    Counter1, Counter2, Counter3
)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 111.111111111111111111 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 222.222222222222222222 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 333.333333333333333333 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 444.444444444444444444 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 555.555555555555555555 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 11.11 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 22.22 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 33.33 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 44.44 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 55.55 AS MONEY),
    'Text1 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('A', 200),
    'Text2 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('B', 200),
    'Text3 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('C', 200),
    'Text4 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('D', 200),
    'Text5 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('E', 200),
    'CODE1-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'CODE2-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'CODE3-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'CODE4-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'CODE5-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 10,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 100
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate 100-column simple table
INSERT INTO dbo.Test_100_Simple (
    S01, S02, S03, S04, S05, S06, S07, S08, S09, S10,
    I01, I02, I03, I04, I05
)
SELECT TOP 500
    'S01-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S02-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S03-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S04-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S05-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S06-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S07-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S08-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S09-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'S10-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 2,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 3,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 4,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 5
FROM sys.objects s1 CROSS JOIN sys.objects s2;

PRINT 'Remaining test tables populated successfully!';
GO