-- Populate compatibility test tables with different row volumes
USE StackOverflowMini;
GO

PRINT 'Populating compatibility test tables...';

-- Populate individual data type tests with 1K rows each
INSERT INTO dbo.Test_Decimal_Only (Amount1, Amount2, Amount3)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 123.456789012345678901 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 987.654321098765432109 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 456.789012345678901234 AS DECIMAL(38,18))
FROM sys.objects s1 CROSS JOIN sys.objects s2;

INSERT INTO dbo.Test_Money_Only (Price1, Price2, Price3)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 1.23 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 4.56 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 7.89 AS MONEY)
FROM sys.objects s1 CROSS JOIN sys.objects s2;

INSERT INTO dbo.Test_VarcharMax_Only (LargeText1, LargeText2, LargeText3)
SELECT TOP 1000
    'Large text 1 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('Content. ', 100),
    'Large text 2 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('Data. ', 100),
    'Large text 3 for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('Information. ', 100)
FROM sys.objects s1 CROSS JOIN sys.objects s2;

INSERT INTO dbo.Test_Mixed_Problematic (Amount, Price, LargeText)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 999.999999999999999999 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 12.34 AS MONEY),
    'Mixed test row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('Complex data. ', 50)
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate 10-column test with 5K rows
INSERT INTO dbo.Test_10_Columns (Col1, Col2, Col3, Col4, Col5, Val1, Val2, Val3, Val4)
SELECT TOP 5000
    'Col1-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'Col2-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'Col3-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'Col4-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    'Col5-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 2,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 3,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 4
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate 25-column test with 2K rows
INSERT INTO dbo.Test_25_Columns (
    Col01, Col02, Col03, Col04, Col05, Col06, Col07, Col08, Col09, Col10,
    Col11, Col12, Col13, Col14, Col15, Val01, Val02, Val03, Val04, Val05,
    Flag1, Flag2, Flag3
)
SELECT TOP 2000
    'C01-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C02-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C03-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C04-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C05-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C06-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C07-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C08-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C09-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C10-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C11-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C12-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C13-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C14-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    'C15-' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 2,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 3,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 4,
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 5,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 2 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 3 = 0 THEN 1 ELSE 0 END,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 5 = 0 THEN 1 ELSE 0 END
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate complex type tests
INSERT INTO dbo.Test_10_Complex (Amount1, Amount2, Price1, Price2, LargeText, StandardText, Counter, Flag)
SELECT TOP 2000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 123.456789012345678901 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 987.654321098765432109 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 12.34 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 56.78 AS MONEY),
    'Complex large text for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)) + '. ' + REPLICATE('Detailed content. ', 30),
    'Standard text for row ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50)),
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)),
    CASE WHEN ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 2 = 0 THEN 1 ELSE 0 END
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate minimal test with 10K rows
INSERT INTO dbo.Test_Minimal (SimpleText)
SELECT TOP 10000
    'Simple text ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(50))
FROM sys.objects s1 CROSS JOIN sys.objects s2;

-- Populate specific problem type tests
INSERT INTO dbo.Test_VarcharMax_Heavy (
    Text01, Text02, Text03, Text04, Text05, Text06, Text07, Text08, Text09, Text10,
    Text11, Text12, Text13, Text14, Text15
)
SELECT TOP 500
    'Text01 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('A', 1000),
    'Text02 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('B', 1000),
    'Text03 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('C', 1000),
    'Text04 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('D', 1000),
    'Text05 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('E', 1000),
    'Text06 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('F', 1000),
    'Text07 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('G', 1000),
    'Text08 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('H', 1000),
    'Text09 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('I', 1000),
    'Text10 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('J', 1000),
    'Text11 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('K', 1000),
    'Text12 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('L', 1000),
    'Text13 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('M', 1000),
    'Text14 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('N', 1000),
    'Text15 ' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(10)) + ' ' + REPLICATE('O', 1000)
FROM sys.objects s1 CROSS JOIN sys.objects s2;

INSERT INTO dbo.Test_Decimal_Heavy (
    Amount01, Amount02, Amount03, Amount04, Amount05, Amount06, Amount07, Amount08, Amount09, Amount10,
    Amount11, Amount12, Amount13, Amount14, Amount15
)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 111.111111111111111111 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 222.222222222222222222 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 333.333333333333333333 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 444.444444444444444444 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 555.555555555555555555 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 666.666666666666666666 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 777.777777777777777777 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 888.888888888888888888 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 999.999999999999999999 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 101.010101010101010101 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 121.212121212121212121 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 131.313131313131313131 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 141.414141414141414141 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 151.515151515151515151 AS DECIMAL(38,18)),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 161.616161616161616161 AS DECIMAL(38,18))
FROM sys.objects s1 CROSS JOIN sys.objects s2;

INSERT INTO dbo.Test_Money_Heavy (
    Price01, Price02, Price03, Price04, Price05, Price06, Price07, Price08, Price09, Price10,
    Price11, Price12, Price13, Price14, Price15
)
SELECT TOP 1000
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 11.11 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 22.22 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 33.33 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 44.44 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 55.55 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 66.66 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 77.77 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 88.88 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 99.99 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 10.10 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 12.12 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 13.13 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 14.14 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 15.15 AS MONEY),
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) * 16.16 AS MONEY)
FROM sys.objects s1 CROSS JOIN sys.objects s2;

PRINT 'Compatibility test data population completed!';

-- Show row counts for verification
SELECT 'Test_Decimal_Only' as TableName, COUNT(*) as RecordCount FROM dbo.Test_Decimal_Only
UNION ALL SELECT 'Test_Money_Only', COUNT(*) FROM dbo.Test_Money_Only
UNION ALL SELECT 'Test_VarcharMax_Only', COUNT(*) FROM dbo.Test_VarcharMax_Only
UNION ALL SELECT 'Test_Mixed_Problematic', COUNT(*) FROM dbo.Test_Mixed_Problematic
UNION ALL SELECT 'Test_10_Columns', COUNT(*) FROM dbo.Test_10_Columns
UNION ALL SELECT 'Test_25_Columns', COUNT(*) FROM dbo.Test_25_Columns
UNION ALL SELECT 'Test_10_Complex', COUNT(*) FROM dbo.Test_10_Complex
UNION ALL SELECT 'Test_Minimal', COUNT(*) FROM dbo.Test_Minimal
UNION ALL SELECT 'Test_VarcharMax_Heavy', COUNT(*) FROM dbo.Test_VarcharMax_Heavy
UNION ALL SELECT 'Test_Decimal_Heavy', COUNT(*) FROM dbo.Test_Decimal_Heavy
UNION ALL SELECT 'Test_Money_Heavy', COUNT(*) FROM dbo.Test_Money_Heavy;

GO